FROM golang:1.23.4 as build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /chat ./cmd/chat

ENTRYPOINT [ "/chat" ]

# Dockerfile construye una aplicación Go, la compila para Linux y establece el ejecutable como el punto de entrada del contenedor.
#hola